# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: false

language: node_js
node_js:
  - '4'
  - '6'
  - 'stable'
cache: yarn

# Make Greenkeeper work with lockfiles:
# https://github.com/greenkeeperio/greenkeeper-lockfile/tree/f62f2f3e33cd1dd349c2898e0129c693cbc5804d#yarn
env:
  global:
    secure: F0ZWMvFdW7WgdhDvpJlT6FowsHMIU6+VOi0i6INIS5bi6FBHDVm84X4ICDW4fvkIvaCPwSgfSTvFOoU9ZwsNJwQxRwNyKYQW44DiXXV4LD4ToD664jQPbFduOXHepSVGL5kFwWg6UX6YZ4TTHdkvJl32UOoCNhMR3yZoYin1dPDNWgkCKPteTAmGPpWTPyY/VBLCcu5di8BXT1nSaJI7x/NPDixkGPnDE5Zvux2MocbLrzzrZD9Ep9JRCGzCtY8nD1g2o2ZSkFgsiD+A5jkbVvnNFcUtpUBrtGzhKjc1xM4B9/C8TORS7mABhw9+qdUBBaU0zTDeUCLIlx6VVIuZKGj8IYCexXBZm2Kyupekdn1c5QymjFV1mTpBCwxPNL71fhww5EnTO4ewIZf939Q1UnRTjdz4Dl1e5CFTTN0AZ1iDQtgI58ZD93FjHMiyvSqIBn1h6dKlzf3ww8Jc2NNKD1h4KHRuBcJc7rCBZ8bR2Pq3Ur1KUiHORY7NKZjR/O85raHtGh4q6wuh4W8RxZ2WlLCGL6dw0lQRcoW4uN2rrVYElwGQqIuwEiIpqPCk75sYP8nku/NfvG3x65gufZIV7PkRF4wL0C2sqWPWikVoVINn9gC/kIC8MQ0dQ6TfQ3Dk92jSUzzTOyIKYxrKtgza9tsEmqGzkbD1lv0W1lYFTwM=

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
